---
# tasks file for pre-checks
- name: load playbook - check resource group 
  include_tasks: 01_check_rg_exist.yml
- name: load playbook - check virtual network
  include_tasks: 02_check_vnet_exist.yml
- name: load playbook - check subnet
  include_tasks: 03_check_subnet_exist.yml
    #- name: load playbook - check load Balancer
    #include_tasks: 04_check_lb_name_exist.yml
